services:
  postgres:
    container_name: ms_pg_sql
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./db_scripts:/docker-entrypoint-initdb.d
    ports:
      - 5433:5432
    networks:
      - ecotrack-net
    restart: unless-stopped

  ecotrack-api:
    container_name: ecotrack-api
    image: ecotrack-api
    environment:
      - PORT
      - DB_HOST
      - DB_PORT
      - DB_USER
      - DB_NAME
      - DB_PASSWORD
      - DB_SCHEMA
      - JWT_SECRET
    ports:
      - "4200:4200"
    networks:
      - ecotrack-net
    depends_on:
      - postgres
    restart: always
    healthcheck:
      timeout: 10s
      retries: 10

networks:
  ecotrack-net:
    driver: bridge

volumes:
  postgres:
  pgadmin:
