export enum Type {
  TAREA_APAGAR_EQUIPOS = "TAREA_APAGAR_EQUIPOS",
  TAREA_RECICLAJE = "TAREA_RECICLAJE",
  TAREA_MOVILIDAD_SOSTENIBLE = "TAREA_MOVILIDAD_SOSTENIBLE",
  TAREA_USO_REUTILIZABLES = "TAREA_USO_REUTILIZABLES",
  TAREA_AHORRO_AGUA = "TAREA_AHORRO_AGUA",
  TAREA_COMPENSACION_CO2 = "TAREA_COMPENSACION_CO2",
  TAREA_EFICIENCIA_ENERGETICA = "TAREA_EFICIENCIA_ENERGETICA",
  TAREA_CAPACITACION_AMBIENTAL = "TAREA_CAPACITACION_AMBIENTAL",
  TAREA_VOLUNTARIADO_AMBIENTAL = "TAREA_VOLUNTARIADO_AMBIENTAL",
}
