export enum Type {
  INSIGNIA_ECOAHORRO = "INSIGNIA_ECOAHORRO",
  INSIGNIA_RECICLADOR = "INSIGNIA_RECICLADOR",
  INSIGNIA_MOVILIDAD_VERDE = "INSIGNIA_MOVILIDAD_VERDE",
  INSIGNIA_CONSUMO_CONSCIENTE = "INSIGNIA_CONSUMO_CONSCIENTE",
  INSIGNIA_HUELLA_ZERO = "INSIGNIA_HUELLA_ZERO",
  INSIGNIA_PROTECTOR_DEL_AGUA = "INSIGNIA_PROTECTOR_DEL_AGUA",
  INSIGNIA_EMBAJADOR_VERDE = "INSIGNIA_EMBAJADOR_VERDE",
}
